### ISSUE TITLE
Explore how `rmarkdown::render()` works with targets

### ISSUE THREAD

**Issue by msleckman** [USGS-VIZLAB/saline-lakes#34]
See following code, which can also be found in #32 [here](https://github.com/USGS-VIZLAB/saline-lakes/pull/32/files#r989227102):  

```
  ## Render Markdown #
  ## built in a {} fun chunk to be able to export file path and save a 'file' target
  ## Note: the input Rmd for the rmarkdown::render() function requires that the input sits in root folder of WD, otherwise is resets the wd for you.
  ## Get crytic message - mine was that the `4_reports/out/` isn't a directory.
  tar_target(
    p4_markdown,
    {output_file <- '4_reports/out/watershed_extent_update_0928.html'
    rmarkdown::render(input = 'watershed_extent_update_0928.Rmd',
                      output_format = 'html_document',
                      output_file = output_file,
                      quiet = TRUE)
    return(output_file)
    },
    format = 'file')

)

```

Noticeable issues: 
1. `input` param seems to only want a file that lives in root of wd. It looks like it resets the wd where this file is in, and therefore cannot output to a different directory, unless maybe if that location is a child folder from where the `Rmd` is. We could potentially place the `.Rmd` in `4_reports` and have it export to `4_reports/out`(haven't tried), but that's not the ideal outcome we want. Ideally, I'd like to set this up such that the `Rmd` is a src file, and the param `input = 4_reports/src/watershed_extent_update_0928.Rmd` while param output_file is: `output_file = output_file`. Is there a way to make this possible?
2. How do upstream targets link up to an `.Rmd` ? Seems like they must be built before rendering tar_make(p4_markdown) and does not track order of targets like regular scripts. With `tar_make()` on it's own, the markdown doesn't find it's upstream targets.

**Comment by jesse-ross** [comment]
@padilla410  one of those two has `reporting` in its name, and the other has `report`!

@msleckman I got curious and looked at `rmarkdown`: it looks like it should have the ability to use a relative path for output. So that might help; maybe you could do something like this?

```r
  tar_target(
    p4_markdown,
    {input_file <- '4_reports/src/watershed_extent_update_0928.html',
    real_output_file <- '4_reports/out/watershed_extent_update_0928.html',
    rmarkdown::render(input = input_file,
                      output_format = 'html_document',
                      # CAREFULLY WRITTEN COMMENT ABOUT WHY YOU HAVE TO DO THE AWFUL HACK IN THE LINE BELOW
                      output_file = sub("4_reports/src", "../..", real_output_file), 
                      quiet = TRUE)
    return(real_output_file)
    },
    format = 'file')
```
